source 'https://rubygems.org'

gem 'chef'
gem 'berkshelf'

group :test do
  gem 'tailor'
  gem 'strainer'
  gem 'foodcritic'
  gem 'chefspec'
end

group :integration do
  gem 'test-kitchen', '~> 1.0.0.beta'
  gem 'kitchen-vagrant'
  gem 'serverspec'
end
